### ISSUE TITLE
Some Enhancements 📝

### ISSUE THREAD

**Issue by lianaling** [lianaling/art-gallery-website#25]
### Checklist 📋

- [x] Add art count in User.aspx
- [x] Implement share` button functions
- [x] Add Dashboard.aspx route & validation
- [x] Remove save from Favourite collections (delete)
- [x] Add visual feedback when saving/removing from Favourite
- [x] Solve All saves logic parsing & display error
- [x] Remove duplicates from All saves
- [x] List the saved Favourite collection name under each art in All saves
- [x] Solve `All saves` logic parsing & display error
- [x] Remove duplicates from `All saves`
- [x] List the saved `Favourite` collection name under each art in `All saves`
- [x] Implement `like` button (insert & delete)
- [x] Add `Favourite Detail Page` that will be linked to `Art Detail Page`
- [x] Remove commented (discarded) code for easier reading

### Description 📝

Some enhancements that can be done before `Part 1` deadline.

### Additional Info 🗨️

`None`

**Comment by marcustut** [comment]
Completed
