### ISSUE TITLE
🐛 `Vue` seems to not be working properly

### ISSUE THREAD

**Issue by lianaling** [lianaling/art-gallery-website#9]
**Describe the bug**
`Vue` does not pick up the `Tailwind` css as expected when the HTML code is put in `<template>` header. I have removed the HTML code from `User.vue` file to the `User.aspx` `asp:Content` container to see if `Tailwind` is working, and it is working fine when placed in the `aspx` file. However, `Vue` seems to have [replicated](#replication) a portion of the HTML code despite having empty code in `<template>`. I have restarted Visual Studio, Visual Studio Code and Git Bash respectively and rerun `yarn dev` multiple times to no avail.

**To Reproduce**
1. Go to `user-page` branch
2. Cut and paste the HTML code in `User.aspx` to `User.vue` under the `<template>` header
3. Run `User.aspx`
4. Change CSS settings
5. See error

**Expected behavior**
`Vue` should pick up the `Tailwind` css and change UI when the browser is refreshed.

**Screenshots**
###### Replication
![image](https://user-images.githubusercontent.com/68136684/125155821-de8b1b80-e194-11eb-9bc8-d1e8b7d1ab38.png)

###### Errors
E.g., the below `Liana Ling` will not change its font size when `text-xl` is changed to `text-4xl`.
![image](https://user-images.githubusercontent.com/68136684/125155715-54db4e00-e194-11eb-838b-eff91037d8d4.png)

**Comment by marcustut** [comment]
I will check this out on your branch later and see what happened

**Comment by marcustut** [comment]
Ehh it's working perfectly fine for me though, did you run the dev server? Using the `yarn dev` command

**Comment by lianaling** [comment]
> Ehh it's working perfectly fine for me though, did the webpack dev server recompiles your code? from the `yarn dev` command
> 
>  2021-07-10.21-09-35.mp4

I tried just now and it's working fine too. I hate to say this cliche but I have to make a temporary conclusion that it might be Windows' problem again. If anything happens I'll add to this thread but for now I'll close it. Thanks and sorry for the inconvenience caused! :')
